version: '3.8'

services:
  # Dev environment extensions
  
  # MongoDB UI - Configure to connect to your external MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: ticket-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_HOST:-localhost}
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER:-}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD:-}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGODB_AUTH_SOURCE:-admin}
    networks:
      - ticket-network

  # PostgreSQL UI - Configure to connect to your external PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ticket-pgadmin
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - ticket-network

  # Redis UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ticket-redis-commander
    ports:
      - "8083:8081"
    environment:
      - REDIS_HOSTS=local:${REDIS_HOST:-redis}:${REDIS_PORT:-6379}:${REDIS_DB_INDEX:-0}:${REDIS_PASSWORD:-}
    depends_on:
      - redis
    networks:
      - ticket-network

networks:
  ticket-network:
    external: true