version: '3.8'

services:
  # Dev environment extensions
  
  # MongoDB UI
  mongo-express:
    image: mongo-express:latest
    container_name: ticket-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - ticket-network

  # PostgreSQL UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ticket-pgadmin
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - ticket-network

  # Redis UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ticket-redis-commander
    ports:
      - "8083:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - ticket-network

networks:
  ticket-network:
    external: true