version: '3'

services:
  notification-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ticket-network
      
  notification-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ticket-network
      
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    networks:
      - ticket-network

networks:
  ticket-network:
    external: true